packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  react: 19.0.0-rc-9c6806964f-20240703
  react-dom: 19.0.0-rc-9c6806964f-20240703
  typescript: ^5.5.3
  effect: ^3.5.1

  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
