packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@remix-run/dev": ^2.11.2
  "@remix-run/node": ^2.11.2
  "@remix-run/react": ^2.11.2
  "@types/node": ^22.5.4
  effect: ^3.7.2
  react: 19.0.0-rc-a03254bc-20240905
  react-dom: 19.0.0-rc-a03254bc-20240905
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  typescript: ^5.6.2
