packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@remix-run/dev": ^2.10.3
  "@remix-run/node": ^2.10.3
  "@remix-run/react": ^2.10.3
  "@remix-run/serve": ^2.10.3
  "@types/node": ^20.14.11
  effect: ^3.5.6
  react: 19.0.0-rc-d025ddd3-20240722
  react-dom: 19.0.0-rc-d025ddd3-20240722
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  typescript: ^5.5.3
